on:
  watch:
    types: started


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: init
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: build
        run: |
          mkdir /opt/bin
          git clone --depth=1 https://github.com/hu-min/padavan.git /opt/rt-n56u
          cd /opt/rt-n56u/toolchain-mipsel
          sh dl_toolchain.sh
          cd /opt/rt-n56u/trunk

          # remove the dnsmasq cache size config
          sed -i 's/fprintf(fp, "cache-size=%d\\n", DNS_RELAY_CACHE_MAX);/\/\/fprintf(fp, "cache-size=%d\\n", DNS_RELAY_CACHE_MAX);/' user/rc/services_ex.c
          # sed -i 's/DNS_RELAY_CACHE_MAX\t\t1024/DNS_RELAY_CACHE_MAX\t\t10000/' user/rc/rc.h

          # enlarge the storage size
           sed -i 's/CONFIG_MTD_STORE_PART_SIZ=0x200000/CONFIG_MTD_STORE_PART_SIZ=0x600000/' configs/boards/K2P-USB/kernel-3.4.x.config
           sed -i 's/mtd_part_size=65536/mtd_part_size=6291456/' user/scripts/mtd_storage.sh

          # logo
          https://raw.githubusercontent.com/hanwckf/rt-n56u/master/trunk/user/www/n56u_ribbon_fixed/bootstrap/img/asus_logo.png  -O user/www/n56u_ribbon_fixed/bootstrap/img/asus_logo.png

          # build-in smartdns
          rm -rf user/smartdns
          mkdir -p user/smartdns
          wget -P user/smartdns/ https://raw.githubusercontent.com/hu-min/v2ray-padavan-doh/master/padavan/smartdns/Makefile
          sed -i '$a\export SSL_CERT_FILE=/usr/lib/cacert.pem' user/scripts/profile
          # remove ui
          sed -i 's/found_app_smartdns = 1/found_app_smartdns = 0/' user/httpd/web_ex.c
	  
          # build-in xray
          rm -rf user/xray
          mkdir -p user/xray
          wget -P user/xray/ https://raw.githubusercontent.com/felix-fly/v2ray-padavan-doh/master/padavan/xray/Makefile

      - name: build K2P-USB
          wget https://raw.githubusercontent.com/hu-min/v2ray-padavan-doh/master/k2p.config -O configs/templates/K2P-USB.config
          fakeroot ./build_firmware_modify K2P-USB
          mv /opt/rt-n56u/trunk/images/*.trx /opt/bin/k2p-usb.trx

      - name: Upload artifact
        uses: "actions/upload-artifact@master"
        with:
          name: Upload artifact
          path: /opt/bin
